# Data Analysis Pipeline
### 1) Load Data

In [39]:
import pandas as pd
import numpy as np

In [40]:
data = pd.read_csv("database.csv")
data.head()

/Users/garnoor/opt/miniconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3169: DtypeWarning: Columns (7,16,62,64,65,67,68,78) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Transmission Descriptor,Engine Index,Engine Descriptor,...,Hours to Charge (AC 240V),Composite City MPG,Composite Highway MPG,Composite Combined MPG,Range (FT1),City Range (FT1),Highway Range (FT1),Range (FT2),City Range (FT2),Highway Range (FT2)
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9001,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9005,(FFS) CA model,...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9002,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9006,(FFS) CA model,...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,NaN,1830,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0

In [41]:
include = data.describe(percentiles=None, include= np.number, exclude=None)
include

,Vehicle ID,Year,Engine Index,Engine Cylinders,Engine Displacement,City MPG (FT1),Unrounded City MPG (FT1),City MPG (FT2),Unrounded City MPG (FT2),City Gasoline Consumption (CD),...,Hours to Charge (240V),Hours to Charge (AC 240V),Composite City MPG,Composite Highway MPG,Composite Combined MPG,Range (FT1),City Range (FT1),Highway Range (FT1),City Range (FT2),Highway Range (FT2)
count,38113.000000,38113.000000,38113.000000,37977.000000,37979.000000,38113.000000,38113.000000,38113.000000,38113.000000,38113.000000,...,38113.000000,38113.000000,38113.000000,38113.000000,38113.000000,38113.000000,38113.000000,38113.000000,38113.000000,38113.000000
mean,19170.638496,2000.194527,8799.389001,5.736656,3.317583,17.981109,4.606426,0.546218,0.386633,0.000432,...,0.027635,0.005549,0.082203,0.080891,0.081311,0.469708,0.426249,0.419197,0.043973,0.040051
std,11134.878665,10.464573,17781.058490,1.752254,1.361995,6.849728,10.113963,4.109282,3.861179,0.039976,...,0.473685,0.161014,2.156682,2.052187,2.097794,9.352069,9.104702,9.315914,1.311628,1.169281
min,1.000000,1984.000000,0.000000,2.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9529.000000,1991.000000,0.000000,4.000000,2.200000,15.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,19058.000000,2001.000000,212.000000,6.000000,3.000000,17.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,28779.000000,2009.000000,4451.000000,6.000000,4.300000,20.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,38542.000000,2017.000000,69102.000000,16.000000,8.400000,150.000000,150.000000,145.000000,145.083500,5.350000,...,12.000000,7.000000,97.000000,81.000000,88.000000,315.000000,305.900000,346.900000,103.030000,90.550000

In [42]:
exclude= data.describe(percentiles=None, include=None, exclude=np.number)
exclude

,Make,Model,Class,Drive,Transmission,Transmission Descriptor,Engine Descriptor,Turbocharger,Supercharger,Fuel Type,...,Gas Guzzler Tax,My MPG Data,Start Stop Technology,Alternative Fuel/Technology,Electric Motor,Manufacturer Code,Gasoline/Electricity Blended (CD),Vehicle Charger,Alternate Charger,Range (FT2)
count,38113,38113,38113,36924,38102,15045,22693,5239,693,38113,...,2296,38113,6443,3047,604,7319,38113,48,46,1433
unique,133,3748,34,7,46,52,544,1,1,14,...,3,2,2,8,119,45,2,5,4,210
top,Chevrolet,F150 Pickup 2WD,Compact Cars,Front-Wheel Drive,Automatic 4-Speed,CLKUP,(FFS),T,S,Regular,...,G,N,N,FFV,288V Ni-MH,GMX,False,standard charger,80 amp dual charger,290
freq,3810,209,5508,13351,11042,7809,8827,5239,693,25258,...,1317,25552,4677,1345,117,1084,38068,38,38,74

### 2) Clean Data

In [43]:
data1=data.drop(columns=['Unrounded City MPG (FT1)','Unrounded City MPG (FT2)','Highway Range (FT2)','Highway Range (FT1)','City Range (FT1)','City Range (FT2)',
                         'Composite Combined MPG','Composite Highway MPG','Composite City MPG','Manufacturer Code','Vehicle Charger','Alternate Charger','Hours to Charge (120V)'
                         ,'Hours to Charge (240V)','Hours to Charge (AC 240V)','Range (FT2)','4D Passenger Volume','4D Luggage Volume','Hatchback Passenger Volume',
                         'Hatchback Luggage Volume','Electric Motor','Gasoline/Electricity Blended (CD)','Tailpipe CO2 in Grams/Mile (FT2)','GHG Score','GHG Score (Alt Fuel)',
                         'My MPG Data','2D Passenger Volume','2D Luggage Volume','Tailpipe CO2 (FT1)','Tailpipe CO2 in Grams/Mile (FT1)','Tailpipe CO2 (FT2)','Start Stop Technology',
                         'Annual Consumption in Barrels (FT2)','Annual Fuel Cost (FT2)','Engine Index','Combined Electricity Consumption','Combined Gasoline Consumption (CD)','Combined Utility Factor'
                         ,'Gas Guzzler Tax','Range (FT1)','Alternative Fuel/Technology','Unrounded Combined MPG (FT2)','Combined MPG (FT2)','Unrounded Combined MPG (FT1)','Combined MPG (FT1)',
                        'Engine Descriptor','Highway Electricity Consumption','Highway Utility Factor','Unadjusted City MPG (FT1)','Unadjusted Highway MPG (FT1)','Unadjusted City MPG (FT2)',
                         'Unadjusted Highway MPG (FT2)','Transmission Descriptor','Engine Cylinders','Engine Displacement','City Utility Factor','Highway MPG (FT1)','Unrounded Highway MPG (FT1)',
                        'Highway MPG (FT2)','Unrounded Highway MPG (FT2)','Highway Gasoline Consumption (CD)','Turbocharger','Supercharger','Fuel Type 1','Fuel Type 2','City MPG (FT1)','City MPG (FT2)',
                        'City Gasoline Consumption (CD)','City Electricity Consumption'])
data1

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Fuel Type,Annual Fuel Cost (FT1),Save or Spend (5 Year),Annual Consumption in Barrels (FT1),Fuel Economy Score
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,Regular,1750,-2000,16.480500,-1
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,Regular,1750,-2000,16.480500,-1
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,Regular,1650,-1500,15.695714,-1
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,Regular,1650,-1500,15.695714,-1
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,Regular,2050,-3500,19.388824,-1
...,...,...,...,...,...,...,...,...,...,...,...,...
38108,37564,2017,Volvo,XC60 FWD,Small Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),Regular,1350,0,12.677308,6
38109,37547,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),Premium,1900,-2750,14.982273,5
38110,37548,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),Premium,1850,-2500,14.330870,5
38111,37703,2017,Volvo,XC90 AWD PHEV,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),Premium and Electricity,1700,-750,8.652550,7
38112,37687,2017,Volvo,XC90 FWD,Standard Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),Premium,1750,-2000,13.733750,5

In [44]:
data2=data1.dropna()
data2

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Fuel Type,Annual Fuel Cost (FT1),Save or Spend (5 Year),Annual Consumption in Barrels (FT1),Fuel Economy Score
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,Regular,2050,-3500,19.388824,-1
5,28426,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,Regular,2050,-3500,19.388824,-1
6,27549,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,Regular,2700,-6750,25.354615,-1
7,28425,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,Regular,2700,-6750,25.354615,-1
8,27593,1984,American Motors Corporation,Eagle 4WD,Special Purpose Vehicle 4WD,4-Wheel or All-Wheel Drive,Automatic 3-Speed,Regular,2050,-3500,19.388824,-1
...,...,...,...,...,...,...,...,...,...,...,...,...
38108,37564,2017,Volvo,XC60 FWD,Small Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),Regular,1350,0,12.677308,6
38109,37547,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),Premium,1900,-2750,14.982273,5
38110,37548,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),Premium,1850,-2500,14.330870,5
38111,37703,2017,Volvo,XC90 AWD PHEV,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),Premium and Electricity,1700,-750,8.652550,7
38112,37687,2017,Volvo,XC90 FWD,Standard Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),Premium,1750,-2000,13.733750,5

In [45]:
data2 = data2.reset_index(drop=True)
data2

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Fuel Type,Annual Fuel Cost (FT1),Save or Spend (5 Year),Annual Consumption in Barrels (FT1),Fuel Economy Score
0,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,Regular,2050,-3500,19.388824,-1
1,28426,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,Regular,2050,-3500,19.388824,-1
2,27549,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,Regular,2700,-6750,25.354615,-1
3,28425,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,Regular,2700,-6750,25.354615,-1
4,27593,1984,American Motors Corporation,Eagle 4WD,Special Purpose Vehicle 4WD,4-Wheel or All-Wheel Drive,Automatic 3-Speed,Regular,2050,-3500,19.388824,-1
...,...,...,...,...,...,...,...,...,...,...,...,...
36911,37564,2017,Volvo,XC60 FWD,Small Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),Regular,1350,0,12.677308,6
36912,37547,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),Premium,1900,-2750,14.982273,5
36913,37548,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),Premium,1850,-2500,14.330870,5
36914,37703,2017,Volvo,XC90 AWD PHEV,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),Premium and Electricity,1700,-750,8.652550,7
36915,37687,2017,Volvo,XC90 FWD,Standard Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),Premium,1750,-2000,13.733750,5

### 3) Process Data

In [46]:
data2['Overal costs (over 5 years)']= (data2['Annual Fuel Cost (FT1)']*5)-data2['Save or Spend (5 Year)']
data2

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Fuel Type,Annual Fuel Cost (FT1),Save or Spend (5 Year),Annual Consumption in Barrels (FT1),Fuel Economy Score,Overal costs (over 5 years)
0,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,Regular,2050,-3500,19.388824,-1,13750
1,28426,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,Regular,2050,-3500,19.388824,-1,13750
2,27549,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,Regular,2700,-6750,25.354615,-1,20250
3,28425,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,Regular,2700,-6750,25.354615,-1,20250
4,27593,1984,American Motors Corporation,Eagle 4WD,Special Purpose Vehicle 4WD,4-Wheel or All-Wheel Drive,Automatic 3-Speed,Regular,2050,-3500,19.388824,-1,13750
...,...,...,...,...,...,...,...,...,...,...,...,...,...
36911,37564,2017,Volvo,XC60 FWD,Small Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),Regular,1350,0,12.677308,6,6750
36912,37547,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),Premium,1900,-2750,14.982273,5,12250
36913,37548,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),Premium,1850,-2500,14.330870,5,11750
36914,37703,2017,Volvo,XC90 AWD PHEV,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),Premium and Electricity,1700,-750,8.652550,7,9250
36915,37687,2017,Volvo,XC90 FWD,Standard Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),Premium,1750,-2000,13.733750,5,10750

### 4) Wrangle data
- At the moment I dont think that I need to further process my data

# Task 2
### Method chaining

In [72]:
import pandas as pd
import numpy as np

data = pd.read_csv("database.csv")


data1=(pd.DataFrame(data.drop(columns=['Unrounded City MPG (FT1)','Unrounded City MPG (FT2)','Highway Range (FT2)','Highway Range (FT1)','City Range (FT1)','City Range (FT2)',
                         'Composite Combined MPG','Composite Highway MPG','Composite City MPG','Manufacturer Code','Vehicle Charger','Alternate Charger','Hours to Charge (120V)'
                         ,'Hours to Charge (240V)','Hours to Charge (AC 240V)','Range (FT2)','4D Passenger Volume','4D Luggage Volume','Hatchback Passenger Volume',
                         'Hatchback Luggage Volume','Electric Motor','Gasoline/Electricity Blended (CD)','Tailpipe CO2 in Grams/Mile (FT2)','GHG Score','GHG Score (Alt Fuel)',
                         'My MPG Data','2D Passenger Volume','2D Luggage Volume','Tailpipe CO2 (FT1)','Tailpipe CO2 in Grams/Mile (FT1)','Tailpipe CO2 (FT2)','Start Stop Technology',
                         'Annual Consumption in Barrels (FT2)','Annual Fuel Cost (FT2)','Engine Index','Combined Electricity Consumption','Combined Gasoline Consumption (CD)','Combined Utility Factor'
                         ,'Gas Guzzler Tax','Range (FT1)','Alternative Fuel/Technology','Unrounded Combined MPG (FT2)','Combined MPG (FT2)','Unrounded Combined MPG (FT1)','Combined MPG (FT1)',
                        'Engine Descriptor','Highway Electricity Consumption','Highway Utility Factor','Unadjusted City MPG (FT1)','Unadjusted Highway MPG (FT1)','Unadjusted City MPG (FT2)',
                         'Unadjusted Highway MPG (FT2)','Transmission Descriptor','Engine Cylinders','Engine Displacement','City Utility Factor','Highway MPG (FT1)','Unrounded Highway MPG (FT1)',
                        'Highway MPG (FT2)','Unrounded Highway MPG (FT2)','Highway Gasoline Consumption (CD)','Turbocharger','Supercharger','Fuel Type 1','Fuel Type 2','City MPG (FT1)','City MPG (FT2)',
                        'City Gasoline Consumption (CD)','City Electricity Consumption'])
                   .dropna()
                   .reset_index(drop=True)))

data1['Overal costs (over 5 years)']= (data1['Annual Fuel Cost (FT1)']*5)-data2['Save or Spend (5 Year)']
data1

/Users/garnoor/opt/miniconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3169: DtypeWarning: Columns (7,16,62,64,65,67,68,78) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Fuel Type,Annual Fuel Cost (FT1),Save or Spend (5 Year),Annual Consumption in Barrels (FT1),Fuel Economy Score,Overal costs (over 5 years)
0,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,Regular,2050,-3500,19.388824,-1,13750
1,28426,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,Regular,2050,-3500,19.388824,-1,13750
2,27549,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,Regular,2700,-6750,25.354615,-1,20250
3,28425,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,Regular,2700,-6750,25.354615,-1,20250
4,27593,1984,American Motors Corporation,Eagle 4WD,Special Purpose Vehicle 4WD,4-Wheel or All-Wheel Drive,Automatic 3-Speed,Regular,2050,-3500,19.388824,-1,13750
...,...,...,...,...,...,...,...,...,...,...,...,...,...
36911,37564,2017,Volvo,XC60 FWD,Small Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),Regular,1350,0,12.677308,6,6750
36912,37547,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),Premium,1900,-2750,14.982273,5,12250
36913,37548,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),Premium,1850,-2500,14.330870,5,11750
36914,37703,2017,Volvo,XC90 AWD PHEV,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),Premium and Electricity,1700,-750,8.652550,7,9250
36915,37687,2017,Volvo,XC90 FWD,Standard Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),Premium,1750,-2000,13.733750,5,10750

In [83]:
def load_and_process(Data):
    df1=(
    pd.read_csv("database.csv")
    .drop(columns=['Unrounded City MPG (FT1)','Unrounded City MPG (FT2)','Highway Range (FT2)','Highway Range (FT1)','City Range (FT1)','City Range (FT2)',
                         'Composite Combined MPG','Composite Highway MPG','Composite City MPG','Manufacturer Code','Vehicle Charger','Alternate Charger','Hours to Charge (120V)'
                         ,'Hours to Charge (240V)','Hours to Charge (AC 240V)','Range (FT2)','4D Passenger Volume','4D Luggage Volume','Hatchback Passenger Volume',
                         'Hatchback Luggage Volume','Electric Motor','Gasoline/Electricity Blended (CD)','Tailpipe CO2 in Grams/Mile (FT2)','GHG Score','GHG Score (Alt Fuel)',
                         'My MPG Data','2D Passenger Volume','2D Luggage Volume','Tailpipe CO2 (FT1)','Tailpipe CO2 in Grams/Mile (FT1)','Tailpipe CO2 (FT2)','Start Stop Technology',
                         'Annual Consumption in Barrels (FT2)','Annual Fuel Cost (FT2)','Engine Index','Combined Electricity Consumption','Combined Gasoline Consumption (CD)','Combined Utility Factor'
                         ,'Gas Guzzler Tax','Range (FT1)','Alternative Fuel/Technology','Unrounded Combined MPG (FT2)','Combined MPG (FT2)','Unrounded Combined MPG (FT1)','Combined MPG (FT1)',
                        'Engine Descriptor','Highway Electricity Consumption','Highway Utility Factor','Unadjusted City MPG (FT1)','Unadjusted Highway MPG (FT1)','Unadjusted City MPG (FT2)',
                         'Unadjusted Highway MPG (FT2)','Transmission Descriptor','Engine Cylinders','Engine Displacement','City Utility Factor','Highway MPG (FT1)','Unrounded Highway MPG (FT1)',
                        'Highway MPG (FT2)','Unrounded Highway MPG (FT2)','Highway Gasoline Consumption (CD)','Turbocharger','Supercharger','Fuel Type 1','Fuel Type 2','City MPG (FT1)','City MPG (FT2)',
                        'City Gasoline Consumption (CD)','City Electricity Consumption'])
        .dropna()
    .reset_index(drop=True))
    
    df2=df1
    
    return df2